"""
Page 7: Settings
API configuration, thresholds, and data management.
"""

import streamlit as st
import os
from datetime import datetime
import sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from src.database.schema import init_database, reset_database
from src.database.queries import get_all_settings, set_setting, get_setting
from src.market.tastytrade_client import (
    test_connection, get_tastytrade_session, get_accounts, clear_session_cache,
)

st.set_page_config(page_title="Settings | Portfolio Manager", page_icon="⚙️", layout="wide")
from src.utils.branding import setup_branding
setup_branding()
init_database()

st.markdown("""
<style> #MainMenu {visibility: hidden;} footer {visibility: hidden;} </style>
""", unsafe_allow_html=True)

st.markdown("## ⚙️ Settings")

tab1, tab2, tab3, tab4 = st.tabs(["🔌 API Connection", "📏 Thresholds", "🗄️ Data Management", "📖 About"])

# ============================================================
# API CONNECTION
# ============================================================
with tab1:
    st.markdown("### tastytrade API Configuration")

    # Environment
    env = get_setting('tastytrade_environment', 'production')
    environment = st.radio(
        "Environment",
        ['production', 'sandbox'],
        index=0 if env == 'production' else 1,
        horizontal=True,
    )

    st.divider()

    # Auth method
    auth_method = st.radio(
        "Authentication Method",
        ['🔑 OAuth2 (Recommended)', '👤 Username & Password (no 2FA only)'],
        horizontal=True,
    )

    if auth_method == '🔑 OAuth2 (Recommended)':
        st.markdown("### OAuth2 Credentials")

        # Setup guide
        with st.expander("📖 How to get your credentials (one-time setup)", expanded=False):
            st.markdown("""
            **Follow these steps on the tastytrade website:**
            
            1. Log into [my.tastytrade.com](https://my.tastytrade.com)
            2. Go to **My Profile → API → OAuth Applications** tab
            3. You should see your app (e.g. "ffazdane Personal OAuth2 App")
            4. Click **Manage** on your app
            5. Click **Create Grant** — this generates your **Refresh Token**
            6. Copy the **Refresh Token** and paste it below
            7. The **Client Secret** is shown at the top of your app page (click Regenerate if you forgot it)
            
            > 💡 The **Refresh Token never expires** — you only need to do this once!
            
            > ⚠️ The **Client ID** is NOT needed here — only **Client Secret** and **Refresh Token**
            """)

        env_secret = os.getenv('TT_SECRET', '')
        env_refresh = os.getenv('TT_REFRESH', '')

        col1, col2 = st.columns(2)
        with col1:
            client_secret = st.text_input(
                "Client Secret (TT_SECRET)",
                value=env_secret,
                type="password",
                help="From your OAuth app page — the secret shown at the top"
            )
        with col2:
            refresh_token = st.text_input(
                "Refresh Token (TT_REFRESH)",
                value=env_refresh,
                type="password",
                help="Generated by clicking 'Create Grant' on your OAuth app"
            )

        tcol1, tcol2, tcol3 = st.columns(3)
        with tcol1:
            if st.button("🧪 Test Connection", type="primary", key="test_oauth"):
                if not client_secret or not refresh_token:
                    st.error("Please enter both Client Secret and Refresh Token")
                else:
                    with st.spinner("Testing OAuth2 connection..."):
                        success, message = test_connection(
                            client_secret=client_secret,
                            refresh_token=refresh_token,
                            environment=environment,
                        )
                        if success:
                            st.success(f"✅ {message}")
                        else:
                            st.error(message)

        with tcol2:
            if st.button("🔌 Connect & Save", key="connect_oauth"):
                if not client_secret or not refresh_token:
                    st.error("Please enter both Client Secret and Refresh Token")
                else:
                    with st.spinner("Connecting..."):
                        session, error = get_tastytrade_session(
                            client_secret=client_secret,
                            refresh_token=refresh_token,
                            environment=environment,
                        )
                        if error:
                            st.error(error)
                        else:
                            st.session_state.tastytrade_session = session
                            accounts, _ = get_accounts(session)
                            st.session_state.accounts = accounts
                            set_setting('tastytrade_environment', environment)
                            st.success("✅ Connected!")
                            st.rerun()

        with tcol3:
            if st.button("🔄 Disconnect", key="disconnect_oauth"):
                clear_session_cache()
                st.session_state.tastytrade_session = None
                st.session_state.accounts = None
                st.info("Disconnected")
                st.rerun()

        if not env_secret or not env_refresh:
            st.markdown("---")
            st.markdown(
                "💾 **To auto-load on startup**, add to your `.env` file:\n"
                "```\n"
                "TT_SECRET=your_client_secret\n"
                "TT_REFRESH=your_refresh_token\n"
                "```"
            )

    else:
        # Username/Password
        st.markdown("### Username & Password")
        st.warning("⚠️ Only works if 2FA is **DISABLED**. If you have 2FA enabled, use OAuth2 above.")

        env_username = os.getenv('TASTYTRADE_USERNAME', '')
        env_password = os.getenv('TASTYTRADE_PASSWORD', '')

        col1, col2 = st.columns(2)
        with col1:
            username = st.text_input("Username", value=env_username)
        with col2:
            password = st.text_input("Password", value=env_password, type="password")

        tcol1, tcol2, tcol3 = st.columns(3)
        with tcol1:
            if st.button("🧪 Test Connection", type="primary", key="test_pwd"):
                with st.spinner("Testing..."):
                    success, msg = test_connection(username=username, password=password, environment=environment)
                    if success:
                        st.success(f"✅ {msg}")
                    else:
                        st.error(msg)
        with tcol2:
            if st.button("🔌 Connect", key="connect_pwd"):
                with st.spinner("Connecting..."):
                    session, error = get_tastytrade_session(username=username, password=password, environment=environment)
                    if error:
                        st.error(error)
                    else:
                        st.session_state.tastytrade_session = session
                        accounts, _ = get_accounts(session)
                        st.session_state.accounts = accounts
                        set_setting('tastytrade_environment', environment)
                        st.success("✅ Connected!")
                        st.rerun()
        with tcol3:
            if st.button("🔄 Disconnect", key="disconnect_pwd"):
                clear_session_cache()
                st.session_state.tastytrade_session = None
                st.session_state.accounts = None
                st.rerun()

    # Connection status
    st.divider()
    st.markdown("#### Connection Status")
    if st.session_state.get('tastytrade_session'):
        st.success("🟢 Connected to tastytrade")
        if st.session_state.get('accounts'):
            st.markdown("**Accounts:**")
            for acct in st.session_state.accounts:
                st.write(f"  • {acct['account_number']} ({acct['nickname']})")
    else:
        st.warning("🟡 Not connected")

# ============================================================
# THRESHOLDS
# ============================================================
with tab2:
    st.markdown("### Alert & Risk Thresholds")
    settings = get_all_settings()

    s1, s2 = st.columns(2)
    with s1:
        st.markdown("#### Alert Settings")
        profit_target = st.slider("Profit Target (%)", 10, 90, int(settings.get('profit_target_pct', {}).get('value', 50)), 5)
        dte_alert = st.slider("DTE Alert (days)", 1, 30, int(settings.get('dte_alert_days', {}).get('value', 7)), 1)
        strike_proximity = st.slider("Strike Proximity (%)", 1, 10, int(float(settings.get('strike_proximity_pct', {}).get('value', 2))), 1)
    with s2:
        st.markdown("#### Portfolio Limits")
        concentration = st.slider("Max Ticker Concentration (%)", 10, 50, int(settings.get('concentration_limit_pct', {}).get('value', 25)), 5)
        delta_limit = st.number_input("Max Net Delta", 10, 1000, int(settings.get('delta_exposure_limit', {}).get('value', 100)), 10)
        refresh_interval = st.selectbox("Refresh Interval", [60, 120, 300, 600], 2, format_func=lambda x: f"{x//60} min")

    if st.button("💾 Save Settings", type="primary", key="save_thresholds"):
        set_setting('profit_target_pct', str(profit_target), 'Profit target percentage')
        set_setting('dte_alert_days', str(dte_alert), 'DTE threshold')
        set_setting('strike_proximity_pct', str(strike_proximity), 'Strike proximity %')
        set_setting('concentration_limit_pct', str(concentration), 'Concentration limit')
        set_setting('delta_exposure_limit', str(delta_limit), 'Delta limit')
        set_setting('refresh_interval_sec', str(refresh_interval), 'Refresh interval')
        st.success("✅ Settings saved!")

# ============================================================
# DATA MANAGEMENT
# ============================================================
with tab3:
    st.markdown("### Data Management")
    if st.button("📤 Export Database Backup"):
        import shutil
        from src.database.connection import DB_PATH
        if os.path.exists(DB_PATH):
            backup_name = f"portfolio_backup_{datetime.now().strftime('%Y%m%d_%H%M%S')}.db"
            backup_path = os.path.join(os.path.dirname(DB_PATH), backup_name)
            shutil.copy2(DB_PATH, backup_path)
            st.success(f"✅ Backup: {backup_name}")
        else:
            st.warning("No database file found.")

    st.divider()
    st.markdown("#### ⚠️ Danger Zone")
    st.warning("Destructive — cannot be undone!")
    if st.checkbox("I understand this will delete ALL data", key="confirm_reset"):
        if st.button("🗑️ Reset Database"):
            reset_database()
            st.session_state.clear()
            init_database()
            st.success("Database reset.")
            st.rerun()

# ============================================================
# ABOUT
# ============================================================
with tab4:
    st.markdown("""
    ### About Options Portfolio Manager
    **Version:** 1.0.0

    **Auth:** OAuth2 (Client Secret + Refresh Token) or Username/Password
    
    **Data Sources:** tastytrade API, Broker CSV/Excel imports, Yahoo Finance fallback

    **Principles:** Transactions as source of truth. Never delete — use status transitions.
    """)
